# Site settings
title: Irena Černovsek
email: irenacernovsek@gmail.com
description: "Unikatni nakit"
baseurl: ""
url: "http://irenacernovsek.si/"


# Build settings
markdown: kramdown
permalink: pretty


sass:
    sass_dir: assets/stylesheet/_sass
    style: compressed


